version: '2'
services:

    data:
        build: ./data
        volumes: 
            - ${WEB_APPLICATION}:/data:rw
        tty: true
        networks:
            - backend

    # mysql
    mysql:
        build: 
          context: ./mysql
          args:
              - MYSQL_VERSION=${MYSQL_VERSION}
        #image: mysql
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            #数据库的数据持久化到磁盘
            - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        networks:
            - backend

    redis:
        build: ./redis
        #image: redis-server
        volumes:
            - ${DATA_SAVE_PATH}/redis:/data
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - backend

    php-fpm:
        build: ./php-fpm
        #image: php-fpm
        volumes_from:
            - data
        volumes:
            - ${DATA_SAVE_PATH}/php/php.ini:/usr/local/etc/php/php.ini:ro
        ports:
            - "${NGINX_PHP_UPSTREAM_PORT}:9000"
        depends_on:
            - mysql
            - redis
        links:
            - mysql:db;
            - redis:redis
        networks:
            - backend

    # web
    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
                - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        #image: nginx-server
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        links:
            - php-fpm:php
        volumes_from:
            - data
        volumes:
            #server配置
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            #日志
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: "bridge"
    backend:
        driver: "bridge"